"""Report plugin — auto-generate research report from upstream outputs."""

import json
from datetime import datetime
from pathlib import Path

from ..core.plugin import Plugin, PluginResult


REPORT_TEMPLATE = """# ViroScope Analysis Report

**Generated:** {date}
**Tool:** ViroScope OS v{version}

---

## 1. Summary

| Metric | Value |
|--------|-------|
| Sequences analyzed | {n_seqs} |
| Alignment length | {align_len} bp |
| Best-fit model | {model} |
| Log-likelihood | {logl} |
| Mean dN/dS | {dnds} |

## 2. Phylogenetic Tree

```
{ascii_tree}
```

### Tree Statistics

- Tree length: {tree_length}
- Average bootstrap support: {bootstrap}%

## 3. Mutations

- Total mutations: {total_muts}
- Antigenic site mutations: {ant_muts}
  - Site A: {a}
  - Site B: {b}
  - Site C: {c}
  - Site D: {d}
  - Site E: {e}

### Top Mutations by Antigenic Impact

{top_mutations}

## 4. Selection Pressure

| Pair | dN | dS | dN/dS |
|------|-----|-----|-------|
{dnds_table}

**Mean dN/dS:** {mean_dnds} — {dnds_interpretation}

## 5. Clade Distribution

{clades}

## 6. QC Summary

- Input sequences: {input_seqs}
- Passed QC: {passed}
- Failed QC: {failed}
- Duplicates removed: {dupes}

---

*Report generated by ViroScope OS. For questions, consult the AI Scientist Agent.*
"""


def _render_md(report: dict) -> str:
    t = REPORT_TEMPLATE
    m = report.get("mutations", {})
    am = m.get("antigenic_site_counts", {})
    hm = m.get("heatmap", [])
    top5 = hm[:5] if hm else []
    top_str = "\n".join(
        f"- H3-{r['h3_position']}: site {r.get('antigenic_site','?')}" for r in top5
    ) if top5 else "  (no antigenic site mutations)"

    evo = report.get("evolution", {}).get("pairs", [])
    dnds_rows = "\n".join(
        f"| {p.get('pair','?')[:50]} | {p.get('dN','?')} | {p.get('dS','?')} | {p.get('dN_dS','?')} |"
        for p in evo[:10]
    ) if evo else "| - | - | - | - |"

    mean_d = report.get("evolution", {}).get("mean_dN_dS", "?")
    if isinstance(mean_d, (int, float)):
        interp = "Positive selection" if mean_d > 1 else "Purifying selection" if mean_d < 0.5 else "Neutral evolution"
    else:
        interp = "N/A"

    clades = report.get("nextclade", {}).get("clade_distribution", {})
    clade_str = "\n".join(f"- {k}: {v}" for k, v in clades.items()) if clades else "  No clade data"

    tree = report.get("tree", {})
    qc = report.get("qc", {})

    return t.format(
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        version=report.get("version", "0.9.0"),
        n_seqs=tree.get("n_sequences", "?"),
        align_len=tree.get("alignment_length", "?"),
        model=tree.get("best_model", "?"),
        logl=tree.get("log_likelihood", "?"),
        dnds=mean_d,
        ascii_tree=report.get("ascii_tree", "(no tree)"),
        tree_length=tree.get("tree_length", "?"),
        bootstrap=tree.get("bootstrap_support", "?"),
        total_muts=m.get("total_mutations", m.get("n_mutations", "?")),
        ant_muts=sum(am.values()) if am else "?",
        a=am.get("A", 0), b=am.get("B", 0), c=am.get("C", 0), d=am.get("D", 0), e=am.get("E", 0),
        top_mutations=top_str,
        dnds_table=dnds_rows,
        mean_dnds=mean_d,
        dnds_interpretation=interp,
        clades=clade_str,
        input_seqs=qc.get("input_count", qc.get("n_sequences", "?")),
        passed=qc.get("qc_good", qc.get("output_count", "?")),
        failed=qc.get("qc_bad", qc.get("removed_total", "?")),
        dupes=len(qc.get("duplicate_sequences", [])),
    )


class ReportPlugin(Plugin):
    name = "report"
    version = "0.1.0"
    description = "Auto-generate research report from all upstream outputs"

    def run(self, input_data, config=None) -> PluginResult:
        if isinstance(input_data, str):
            try:
                data = json.loads(input_data)
            except json.JSONDecodeError:
                # Assume it's a file with aggregated JSON
                p = Path(input_data)
                if p.exists():
                    data = json.loads(p.read_text(encoding="utf-8"))
                else:
                    return PluginResult(ok=False, errors=["Invalid input: not valid JSON or file"])
        elif isinstance(input_data, dict):
            data = input_data
        else:
            return PluginResult(ok=False, errors=["Input must be JSON dict of aggregated results"])

        md = _render_md(data)
        return PluginResult(
            ok=True,
            data={"report_markdown": md},
        )

    def validate(self): return PluginResult(ok=True)
